### ISSUE TITLE
[BUG] API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=30

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#166]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=30 should return response code 404 Not Found

_Actual Result_: 
**Response code 200 OK
Response body message "success show list camp"**



![Image](https://user-images.githubusercontent.com/38873706/218722089-d31f2457-530d-481c-a237-addb9214539d.PNG)

**Comment by helmimuzkr** [comment]
FIXED - given a page number that exceeds the total number of pages, error code 404 not found will be returned

![image](https://user-images.githubusercontent.com/84892873/219133841-14596a07-8af8-46d1-a4da-3c22037a2f93.png)
