### ISSUE TITLE
[BUG] API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=74

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#167]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=74 should return response code 404 Not Found

_Actual Result_: 
**Response code 200 OK
Response body message "success show list camp"**

**Comment by helmimuzkr** [comment]
FIXED - given a page number that exceeds the total number of pages, error code 404 not found will be returned

![image](https://user-images.githubusercontent.com/84892873/219133258-5ce3827d-8624-4877-9fe5-d80f93c305b6.png)
