### ISSUE TITLE
[BUG] API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=z

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#168]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=z should return response code 404 Not Found

_Actual Result_: 
**Response code 200 OK
Response body message "success show list camp"**



![Image](https://user-images.githubusercontent.com/38873706/218723074-c5095b17-4a45-4656-8f2f-58556420c95a.PNG)

**Comment by helmimuzkr** [comment]
FIXED - given a string in parameter page, error code 404 not found will be returned

![image](https://user-images.githubusercontent.com/84892873/219132968-89dbf89b-e051-46d5-af10-8da3c77dacea.png)
