### ISSUE TITLE
[BUG] API GET LIST ALL CAMPS as USER with INVALID PARAMETER PAGE=ndje

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#169]
API Automation Testing

**Comment by helmimuzkr** [comment]
FIXED - given a string in parameter page, error code 404 not found will be returned

![image](https://user-images.githubusercontent.com/84892873/219132425-e162e82d-9fd2-419c-b34f-197a73557192.png)
