### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with EMPTY DOCUMENT

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#171]
API AUtomation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with EMPTY DOCUMENT should return response code 400 Bad Request

_Actual Result_:
**Respose code 404 Not Found
Response body message "document input not found"**



![Image](https://user-images.githubusercontent.com/38873706/218727332-f5dea464-11fc-41d5-8bf6-394eefd40370.PNG)

**Comment by helmimuzkr** [comment]
FIXED - given an empty document, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219126048-a65f34f6-6c6d-4719-90ff-76c0ef548712.png)
