### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE PRICE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#172]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with INVALID DATA TYPE PRICE should return response code 400 Bad Request

_Actual Result_:
**Response code 404 Not Found
Response body message "not found"**

**Comment by helmimuzkr** [comment]
FIXED - given a string in the price field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219099360-d5ea1518-3f07-4c7e-854c-740864ec3f27.png)
