### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE LATITUDE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#174]
API Automation Testing

**Comment by helmimuzkr** [comment]
FIXED - given a string in the latitude field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219098760-d2f167c4-2626-4a0c-91de-d6c30a716d5a.png)
