### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE LONGITUDE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#175]
API Automation Testing

**Comment by helmimuzkr** [comment]
FIXED - given a string in the longitude field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219098839-0145166d-f20a-4075-b87e-12031d7d55fe.png)
