### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE ADDRESS

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#176]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with INVALID DATA TYPE ADDRESS should return response code 400 Bad Request

_Actual Result_:
**Response code 201 Created
Response body message "success add new camp"**

**Comment by helmimuzkr** [comment]
FIXED - given an integer in the address field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219098373-9c3fe998-254d-4296-93e6-8e7e150bbf33.png)
