### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE DISTANCE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#177]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with INVALID DATA TYPE DISTANCE should return response code 400 Bad Request

_Actual Result_:
**Response code 404 Nt Found
Response body message "not found"**

**Comment by helmimuzkr** [comment]
FIXED - given a string in the distance field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219086666-e518ca13-7032-4672-b675-998967914ca5.png)
