### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE TITLE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#178]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with INVALID DATA TYPE should return response code 400 Bad Request

_Actual Result_:
**Response code 201 Created
Response body message "success add new camp"**

**Comment by helmimuzkr** [comment]
FIXED - given an integer in the title field, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219086180-3d6762f9-95ca-4c41-914e-23a1500e4ba6.png)
