### ISSUE TITLE
[BUG] API POST as HOST ADD NEW CAMP with INVALID DATA TYPE DESCRIPTION

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#179]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST as HOST ADD NEW CAMP with INVALID DATA TYPE DESCRIPTION should return response code 400 Bad Request

_Actual Result_:
**Response code 201 Created
Response body message "success add new camp"**

**Comment by helmimuzkr** [comment]
FIXED - given an integer in the description field, code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219085885-aa0b97b5-20ab-4cc7-8a8f-15e61fb5bae1.png)
