### ISSUE TITLE
[BUG] API POST ADD NEW IMAGE as HOST with VALID path and body

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#180]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST ADD NEW IMAGE as HOST with VALID path and body should succeed then return 201 Created response code

_Actual Result_:
**Response code 200 OK**

**Comment by helmimuzkr** [comment]
FIXED - when successfully add new image, success response 201 created will be returned

![image](https://user-images.githubusercontent.com/84892873/219131956-317ceb2a-480e-405a-af38-f8349b51e1da.png)
