### ISSUE TITLE
[BUG] API POST ADD NEW IMAGE as HOST with INVALID ID IN BODY

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#181]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST ADD NEW IMAGE as HOST with INVALID ID IN BODY should failed then return 404 Not Found

_Actual Result_:
**Response code 500 Internal Server Error
Response body message "internal server error"**

**Comment by helmimuzkr** [comment]
FIXED - given invalid camp_id in body request, error code 404 not found will be returned

![image](https://user-images.githubusercontent.com/84892873/219130687-b3733353-8343-4873-b816-03d2246d2195.png)
