### ISSUE TITLE
[BUG] API POST ADD NEW IMAGE as HOST with EMPTY FILE IMAGE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#182]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST ADD NEW IMAGE as HOST with EMPTY FILE IMAGE should failed then return 400 Bad Request

_Actual Result_:
**Response code 404 Not Found
Response body message "not found"**

**Comment by helmimuzkr** [comment]
FIXED - given an empty file image, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219130307-f73a6afe-3ec4-4e50-b8d4-452ec53ac719.png)

**Comment by helmimuzkr** [comment]
REVISION

![image](https://user-images.githubusercontent.com/84892873/219155500-fde33ab9-9400-4ed3-ad0c-d922449ca364.png)
