### ISSUE TITLE
[BUG] API POST ADD NEW IMAGE as HOST with INVALID FILE TYPE

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#183]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST ADD NEW IMAGE as HOST with INVALID FILE TYPE should failed then return 400 Bad Request

_Actual Result_:
**Response code 200 OK
Response body message "success add new image"**

**Comment by helmimuzkr** [comment]
FIXED - given wrong format, error code 400 bad request will be returned

![image](https://user-images.githubusercontent.com/84892873/219129946-0beca508-517f-483c-89a6-c06dcb1aab02.png)
