### ISSUE TITLE
[BUG] API POST LOGIN as GUEST with blank username

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#184]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST LOGIN as GUEST with blank username should fail then return body message "username is empty"

_Actual Result_:
**not in json object**

**Comment by helmimuzkr** [comment]
FIXED - given a blank input in the password field, a message 'password is empty' will be returned

![image](https://user-images.githubusercontent.com/84892873/219083885-7e6a3e40-a823-4285-b1c4-20fdc231fe0e.png)
