### ISSUE TITLE
[BUG] API POST LOGIN as GUEST with blank password

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#185]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API POST LOGIN as GUEST with blank password should fail then return body message "password is empty"

_Actual Result_:
**not in json object**

![Image](https://user-images.githubusercontent.com/38873706/218774650-8416d57d-0bd0-4a25-abd4-5387ed69b32b.PNG)

**Comment by helmimuzkr** [comment]
FIXED - given a blank input in the password field, a message 'password is empty' will be returned
![image](https://user-images.githubusercontent.com/84892873/219082250-32589e89-8ca2-4035-b74c-482e96836827.png)
