### ISSUE TITLE
[BUG] API PUT A CAMP to DECLINED as ADMIN with VALID PATH, PARAMETER, AND TOKEN

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#186]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API PUT A CAMP to DECLINED as ADMIN with VALID PATH, PARAMETER, AND TOKEN should return response body "success decline camp"

_ Actual Result_:
**Response body message "success reject camp"**

**Comment by helmimuzkr** [comment]
FIXED - now decline message will show "success decline camp"
![image](https://user-images.githubusercontent.com/84892873/219081458-c61cb724-b9d1-4f12-8245-30342b6d60d6.png)
