### ISSUE TITLE
[BUG] API PUT UPDATE A CAMP as HOST with VALID PATH, TOKEN, AND BODY

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#187]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API PUT UPDATE A CAMP as HOST with VALID PATH, TOKEN, AND BODY should return response code 200 OK

_Actual Result_:
**Response code 201 Created**

**Comment by helmimuzkr** [comment]
FIXED
https://github.com/Capstone-campyuk/campyuk-be/issues/189#issuecomment-1431589470
