### ISSUE TITLE
[BUG] API PUT UPDATE A CAMP as HOST with EMPTY CITY, ADDRESS, TITLE, DESCRIPTION, OR DOCUMENT

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#189]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API PUT UPDATE A CAMP as HOST with EMPTY CITY, ADDRESS, TITLE, DESCRIPTION, AND DOCUMENT should return 200 OK

_Actual Result_:
**Response code 201 Created**

**Comment by helmimuzkr** [comment]
FIX - given empty title will return code 200
![image](https://user-images.githubusercontent.com/84892873/219080013-2949d599-c2a3-48a8-ad6d-3f55149d2dc4.png)
