### ISSUE TITLE
[BUG] API PUT UPDATE A CAMP as HOST with INVALID DATA TYPE CITY, ADDRESS, TITLE, OR DESCRIPTION

### ISSUE THREAD

**Issue by alifalmr** [Capstone-campyuk/campyuk-be#190]
API Automation Testing

**Comment by alifalmr** [comment]
_Summary_: API PUT UPDATE A CAMP as HOST with INVALID DATA TYPE CITY, ADDRESS, TITLE, OR DESCRIPTION should return 400 Bad Request

_Actual Result_:
**Response code 201 Created**

![Image](https://user-images.githubusercontent.com/38873706/218818069-27b5801a-226e-4d53-9c4c-a7075229940d.PNG)

**Comment by helmimuzkr** [comment]
FIX - Invalid data type title
![image](https://user-images.githubusercontent.com/84892873/219079444-707768ad-befb-4f22-bd6e-dbf8cafe82e0.png)
